services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build:
      context: .  # Контекст сборки указывает на корневую папку проекта
      dockerfile: Dockerfile  # Используем Dockerfile из корневой директории
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/superset
    volumes:
      - ./app:/app             # Монтируем директорию app в контейнер
      - ./requirements.txt:/app/requirements.txt
      - ./data:/app/data       # Папка, где хранится ваш CSV-файл

  superset:
    build:
      context: ./superset
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - "8088:8088"
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://postgres:postgres@db:5432/superset # Указываем базу данных superset
      SQLALCHEMY_EXAMPLES_URI: ${SQLALCHEMY_EXAMPLES_URI}
      SUPERSET_LOAD_EXAMPLES: ${SUPERSET_LOAD_EXAMPLES}
      SUPERSET_CREATE_ADMIN: ${SUPERSET_CREATE_ADMIN}
      SUPERSET_ADMIN_USERNAME: ${SUPERSET_ADMIN_USERNAME}
      SUPERSET_ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD}
      SUPERSET_ADMIN_FIRSTNAME: ${SUPERSET_ADMIN_FIRSTNAME}
      SUPERSET_ADMIN_LASTNAME: ${SUPERSET_ADMIN_LASTNAME}
      SUPERSET_ADMIN_EMAIL: ${SUPERSET_ADMIN_EMAIL}
      SUPERSET_WEBSERVER_HOST: ${SUPERSET_WEBSERVER_HOST}
      SUPERSET_WEBSERVER_PORT: ${SUPERSET_WEBSERVER_PORT}
      # Здесь указываем фиксированный ключ
      SUPERSET_SECRET_KEY: "jQx2eM7yE+Rdo8nO2fNZpzzjQYPdz+3TdOflEUX0b5B7+BaS7OgdYtfd"
    volumes:
      - superset_home:/app/superset_home

volumes:
  db_data:
  superset_home: